#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

#cookbook 'apt', git: 'https://github.com/fnichol/chef-apt'

cookbook 'apt', '1.5.0'

cookbook 'build-essential', '1.1.2'

cookbook 'sonar', git: 'https://github.com/ctrabold/chef-sonar', ref: '0.0.4'

#cookbook 'jenkins', git: 'https://github.com/fnichol/chef-jenkins'

cookbook 'jenkins', '0.6.3'

cookbook 'nginx', '1.0.2'